services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=school_management'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=school_user'
    ports:
      - '5432:5432'
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - tr-demo-network
  app:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_management
      SPRING_DATASOURCE_USERNAME: school_user
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - tr-demo-network
networks:
  tr-demo-network:
    external: true